# Generated by Django 4.0.3 on 2022-04-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_usertocategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToCategory',
        ),
    ]
